- label: 'Introduction'
  link: '/'
- label: Valkyrie
  items:
    - label: 'Installation'
      link: '/valkyrie/installation'
    - label: 'Customization'
      link: '/valkyrie/customization'
    - label: 'Changelog'
      link: '/valkyrie/changelog'
- label: Athena
  items:
    - label: 'Installation'
      link: '/athena/installation'
    - label: 'Customization'
      link: '/athena/customization'
    - label: 'Changelog'
      link: '/athena/changelog'
- label: Horus
  items:
    - label: 'Installation'
      link: '/horus/installation'
    - label: 'Customization'
      link: '/horus/customization'
    - label: 'Changelog'
      link: '/horus/changelog'