- label: "Introduction"
  link: "/"
- label: "FAQ"
  link: "/faq"
- label: Valkyrie
  items:
    - label: "Features"
      link: "/valkyrie/features"
    - label: "Installation"
      link: "/valkyrie/installation"
    - label: "Customization"
      link: "/valkyrie/customization"
    - label: "Changelog"
      link: "/valkyrie/changelog"
    - label: "Custom Templates"
      link: "/valkyrie/customtemplates"
    - label: "Credits"
      link: "/valkyrie/credits"
- label: Heimdall
  items:
    - label: "Features"
      link: "/heimdall/features"
    - label: "Installation"
      link: "/heimdall/installation"
    - label: "Customization"
      link: "/heimdall/customization"
    - label: "Changelog"
      link: "/heimdall/changelog"
    - label: "Custom Templates"
      link: "/heimdall/customtemplates"
    - label: "Credits"
      link: "/heimdall/credits"
